######################################################################
# Automatically generated by qmake (1.07a) Wed Apr 27 14:29:26 2005
######################################################################

TEMPLATE = lib
INCLUDEPATH += . ../include
DESTDIR = ../lib

# Input
HEADERS += Proxy.h
SOURCES += Proxy.cpp
