# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/newEngine/Proxy
# Target is a library:  

HEADERS += Proxy.h 
SOURCES += Proxy.cpp 
TEMPLATE = lib
INCLUDEPATH += . ../include
DESTDIR = ../lib/
LIBS += -L../lib -lCommon
OBJECTS_DIR = obj
MOC_DIR = moc
CONFIG += debug thread qt opengl warn_on
QT += network
win32{
  CONFIG += console
}
debug {
  #DEFINES += DMALLOC
  #LIBS += -ldmallocthcxx
}
