######################################################################
# Automatically generated by qmake (1.07a) Fri Apr 29 14:00:19 2005
######################################################################

TEMPLATE = lib
INCLUDEPATH += . ../include
DESTDIR = ../lib

# Input
HEADERS += XmlStorage.h
SOURCES += XmlStorage.cpp
