######################################################################
# Automatically generated by qmake (1.07a) Wed Apr 13 15:01:09 2005
######################################################################

TEMPLATE = lib
INCLUDEPATH += .

# Input
HEADERS += Configuration.h
SOURCES += Configuration.cpp
