
######################################################################
# Automatically generated by qmake (1.07a) Wed Apr 13 15:01:09 2005
######################################################################

TEMPLATE = lib
INCLUDEPATH += . ../include/

CONFIG += debug warn_on

# Input
HEADERS += Configuration.h
SOURCES += Configuration.cpp

DESTDIR = ../lib/
LIBS += -L../lib -lCommon
