######################################################################
# Automatically generated by qmake (1.07a) Thu Apr 14 21:24:30 2005
######################################################################

TEMPLATE = lib
INCLUDEPATH += . ../Common/

CONFIG		+= qt opengl warn_on debug thread

# Input
HEADERS += LexDefs.h Lexer.h
SOURCES += Lexer.cpp

LEXSOURCES += mud.lex player.lex

DESTDIR = ../lib/
LIBS += -L../lib/ -lCommon
