######################################################################
# Automatically generated by qmake (1.07a) Fri Apr 15 13:19:32 2005
######################################################################

TEMPLATE = lib
INCLUDEPATH += . ../include/
DESTDIR = ../lib/
LIBS += -L../lib -lCommon

# Input
HEADERS += Parser.h Path.h Approved.h Experimenting.h Syncing.h
SOURCES += Parser.cpp Path.cpp Approved.cpp Experimenting.cpp Syncing.cpp
