######################################################################
# Automatically generated by qmake (1.07a) Fri Jun 17 11:38:03 2005
######################################################################

TEMPLATE = app

INCLUDEPATH += ../include
LIBS += -L../lib -lCommon
OBJECTS_DIR	= obj

CONFIG += debug thread qt opengl warn_on
win32 {
	CONFIG	+= console
}
QT += opengl

DESTDIR = ../bin
# Input
SOURCES += main.cpp
debug {
  #DEFINES += DMALLOC
  #LIBS += -ldmallocthcxx
}