######################################################################
# Automatically generated by qmake (1.07a) Thu Apr 14 21:14:38 2005
######################################################################

TEMPLATE = lib
INCLUDEPATH += .

# Input
HEADERS += TelnetFilter.h
SOURCES += TelnetFilter.cpp
