# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/newEngine
# Target is a subdirs project 

SUBDIRS += Common \
           Lexer \
           Parser \
           Map \
           Storage \
           Filter \
           Display \
           Configuration \
           Proxy \
	   expandora
TEMPLATE = subdirs
